---
- hosts: webservers
  become: true
  tasks:
    - name: Install packages 
      yum:
        name: "httpd"
        state: "present"
    - name: Start the Apache server 
      service:
        name: httpd
        state: started
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html
        
...
